version: "3.9"
services:
  myworker:
    build: .
    volumes:
      - .:/code
      - mylogvolume01:/var/log
    links:
      - myredis
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_ID: ${SESSION_ID}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      PREFIX: ${PREFIX}
      STICKER_PACKNAME: ${STICKER_PACKNAME}
      ALWAYS_ONLINE: ${ALWAYS_ONLINE}
      RMBG_KEY: ${RMBG_KEY}
      LANGUAG: ${LANGUAG}
      WARN_LIMIT: ${WARN_LIMIT}
      FORCE_LOGOUT: ${FORCE_LOGOUT}
      BRAINSHOP: ${BRAINSHOP}
      MAX_UPLOAD: ${MAX_UPLOAD}
      REJECT_CALL: ${REJECT_CALL}
      SUDO: ${SUDO}
      TZ: ${TZ}
      VPS: ${VPS}
      AUTO_STATUS_VIEW: ${AUTO_STATUS_VIEW}
      SEND_READ: ${SEND_READ}
      AJOIN: ${AJOIN}
      DISABLE_START_MESSAGE: ${DISABLE_START_MESSAGE}
      PERSONAL_MESSAGE: ${PERSONAL_MESSAGE}
  myredis:
    image: redis
volumes:
  mylogvolume01: {}
